### ISSUE TITLE
Plugin fails to start

### ISSUE THREAD

**Issue by pcav** [cayetanobv/QGIS-Plugin-worldwide-night#1]
This is the error:

No module named basemap.
See Help for requirements.

**Comment by pcav** [comment]
Installing 
python-mpltoolkits.basemap
solves the issue.
Sorry, dependenalready stated in the About. Please consider adding these packages to OSgeo4W installer and to the qgis package.

**Comment by cayetanobv** [comment]
Hi Paolo,

Exactly, Matplotlib Basemap is a dependency (I need one method for plugin computations). I've controlled the error if the import fails (if you do not have installed this library).
Great idea, I'll see how to propose a new OSgeo4W package. Basemap is a very good (and mature) extension to Matplotlib, created by NOAA's Jeffry Whitaker:
https://github.com/matplotlib/basemap

Thanks!
