### ISSUE TITLE
Please move it under the appropriate menu

### ISSUE THREAD

**Issue by pcav** [cayetanobv/QGIS-Plugin-worldwide-night#2]
Presumably Vector, so it will be easier to find.

**Comment by cayetanobv** [comment]
Moved to Vector category (changed Metadata). Added to new version uploaded to QGIS Python Plugins Repository.

Thanks!

**Comment by cayetanobv** [comment]
Upload to QGIS Python Plugins Repository with this change. It works fine. I'm closing the issue.
Thanks!
