### ISSUE TITLE
``Close`` button missing

### ISSUE THREAD

**Issue by pcav** [cayetanobv/QGIS-Plugin-worldwide-night#3]
At least on Gnome3

**Comment by cayetanobv** [comment]
Hi Paolo,

Added close button. Uploaded new version 0.2 to QGIS Python Plugins Repository.

Thanks!

**Comment by cayetanobv** [comment]
Reinstalled after upload to QGIS Python Plugins Repository. It works fine. I'm closing the issue.
Thanks!
